const orderProduct = [
  {
    avatar_img: "http://tiing-storage.s3.amazonaws.com/product/644708/bo.jpeg",
    note: "áidjaisdaisdij",
    preserve: "íaidjaisdjaijsdaijd",
    updated_at: "2021-09-20T13:51:27.579467",
    id: 19,
    category_id: [4],
    tag: "ádijasidjaisdji",
    location: null,
    price: [
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 1,
        default: true,
      },
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 2,
        default: false,
      },
    ],
    type_product: null,
    total_rate: 0,
    code: "644708",
    status: 1,
    brand: "sidjaisdjaijsdiajd",
    comment: null,
    is_active: true,
    made_in: null,
    belong_to_store: null,
    name: "Test Trái cây",
    image_list: [
      "http://tiing-storage.s3.amazonaws.com/product/644708/bo.jpeg",
    ],
    made_by: null,
    extra: null,
    slug: "test",
    day_to_shipping: "ádijaisdaisdjaisd",
    guide: "áidiasdjiajsdiasdj",
    description: "Test Trái cây",
    created_at: "2021-09-09T15:22:14.181593",
  },
  {
    avatar_img:
      "http://tiing-storage.s3.amazonaws.com/product/111991/thit_ga.jpeg",
    note: null,
    preserve: null,
    updated_at: "2021-09-20T13:09:28.037567",
    id: 26,
    category_id: [2],
    tag: null,
    location: null,
    price: [
      {
        stock: 100,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 1,
        default: true,
      },
    ],
    type_product: null,
    total_rate: 0,
    code: "111991",
    status: 1,
    brand: null,
    comment: null,
    is_active: true,
    made_in: null,
    belong_to_store: null,
    name: "Cá",
    image_list: [
      "http://tiing-storage.s3.amazonaws.com/product/111991/thit_ga.jpeg",
    ],
    made_by: null,
    extra: null,
    slug: "Ca",
    day_to_shipping: null,
    guide: null,
    description: "Cá tươi",
    created_at: "2021-09-15T18:18:36.123942",
  },
  {
    avatar_img:
      "http://tiing-storage.s3.amazonaws.com/product/361495/download.jpeg",
    note: "áidjaisdjiajds",
    preserve: "idasjidajsdijaisd",
    updated_at: "2021-09-10T17:03:42.342505",
    id: 22,
    category_id: 4,
    tag: "ádijaisdjaisd",
    location: null,
    price: [
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 1,
        default: true,
      },
    ],
    type_product: null,
    total_rate: 0,
    code: "361495",
    status: 1,
    brand: "ádajsdijaisdj",
    comment: null,
    is_active: true,
    made_in: null,
    belong_to_store: null,
    name: "quýt",
    image_list: ["http://tiing-storage.s3.amazonaws.com/product/361495/oi.jpg"],
    made_by: null,
    extra: null,
    slug: "quyt",
    day_to_shipping: "íadiajsdijasdijasid",
    guide: "saidjaisdiasjd",
    description: "ádasodaisd",
    created_at: "2021-09-09T15:45:01.445407",
  },
  {
    avatar_img: "http://tiing-storage.s3.amazonaws.com/product/222796/cam.jpg",
    note: "Cam nè",
    preserve: "Cam nè",
    updated_at: "2021-09-12T13:32:39.387527",
    id: 23,
    category_id: 4,
    tag: "Cam nè",
    location: null,
    price: [
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 1,
        default: false,
      },
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 2,
        default: true,
      },
    ],
    type_product: null,
    total_rate: 0,
    code: "222796",
    status: 1,
    brand: "Cam nè",
    comment: null,
    is_active: true,
    made_in: "Test cam madein",
    belong_to_store: null,
    name: "Cam 2",
    image_list: [
      "http://tiing-storage.s3.amazonaws.com/product/222796/cam.jpg",
      "http://tiing-storage.s3.amazonaws.com/product/222796/cam.jpg",
      "http://tiing-storage.s3.amazonaws.com/product/222796/cam.jpg",
    ],
    made_by: "Test cam madeby",
    extra: null,
    slug: "Cam",
    day_to_shipping: "nope",
    guide: "Cam nè",
    description: "Cam nè",
    created_at: "2021-09-09T16:03:37.159390",
  },
  {
    avatar_img: "http://tiing-storage.s3.amazonaws.com/product/381385/buoi.png",
    note: null,
    preserve: null,
    updated_at: "2021-09-14T23:03:28.917197",
    id: 16,
    category_id: [1, 2],
    tag: null,
    location: null,
    price: [
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 1,
        default: true,
      },
    ],
    type_product: null,
    total_rate: 0,
    code: "381385",
    status: 1,
    brand: null,
    comment: null,
    is_active: true,
    made_in: null,
    belong_to_store: null,
    name: "test 2",
    image_list: [
      "http://tiing-storage.s3.amazonaws.com/product/381385/bo.jpeg",
      "http://tiing-storage.s3.amazonaws.com/product/381385/bo.jpeg",
    ],
    made_by: null,
    extra: null,
    slug: "test-2",
    day_to_shipping: null,
    guide: null,
    description: null,
    created_at: "2021-09-07T21:40:21.440070",
  },
  {
    avatar_img:
      "http://tiing-storage.s3.amazonaws.com/product/608472/onion.jpg",
    note: null,
    preserve: null,
    updated_at: "2021-09-10T17:00:13.002558",
    id: 17,
    category_id: 1,
    tag: null,
    location: null,
    price: [
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 1,
        default: true,
      },
      {
        stock: 20,
        price_sale: 50,
        price: 80,
        unit: "kg",
        weight: 1,
        id: 2,
        default: false,
      },
    ],
    type_product: null,
    total_rate: 0,
    code: "608472",
    status: 1,
    brand: null,
    comment: null,
    is_active: true,
    made_in: null,
    belong_to_store: null,
    name: "Hành tím",
    image_list: [
      "http://tiing-storage.s3.amazonaws.com/product/608472/onion.jpg",
      "http://tiing-storage.s3.amazonaws.com/product/608472/onion.jpg",
    ],
    made_by: null,
    extra: null,
    slug: "Hanh-tim",
    day_to_shipping: null,
    guide: null,
    description: null,
    created_at: "2021-09-09T13:15:18.951708",
  },
];

export default orderProduct;
